name: PolPowSmp
favicon: null
layout_spectrum: 0.9638783349655569
typography_spectrum: 0.7412347332574427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5734982662834227
  lightness: 0.16241593030281365
  saturation: 0.4921378588769585
  rhythmicContrast: 0.08484678692184389
purpose: []
